// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestingTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void testing()
    {
        driver.Navigate().GoToUrl("https://elp.duetbd.org/login/index.php");
        driver.Manage().Window.Size = new System.Drawing.Size(677, 738);
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).Click();
        driver.FindElement(By.Id("username")).SendKeys("170042088");
        driver.FindElement(By.Id("password")).Click();
        driver.FindElement(By.Id("password")).SendKeys("*****");
        driver.FindElement(By.Id("loginbtn")).Click();
        driver.FindElement(By.CssSelector(".avatar > .userpicture")).Click();
        driver.FindElement(By.Id("actionmenuaction-6")).Click();
    }
}
